# conf/discriminator/patchgan.yaml
_target_: ainpp_pb_latam.models.gan.discriminator.PatchDiscriminator3D

# Discriminator input channels = (Historical Channels + Future Channels)
# Example: If 1 channel goes in (historical) and 1 comes out (prediction), input_channels must be 2.
input_channels: 1

ndf: 64            # Number of filters in the first layer (base)
n_layers: 1        # Profundidade da rede
norm_type: "instance"