# Base Dataset Configuration (points to the class)
dataset:
  _target_: src.datasets.gsmap.AINPPPBLATAMDataset
  zarr_path: "/prj/ideeps/adriano.almeida/data/ainpp/legacy/AINPP-PB-LATAM.zarr"
  input_timesteps: 12
  output_timesteps: 6
  patch_size: 320
  patch_stride: 320
  consolidated: true
  dtype: "float32"

# DataLoader specific parameters (Training)
train_loader:
  batch_size: 16
  num_workers: 8
  prefetch_factor: 2
  pin_memory: true
  drop_last: true
  shuffle: true

# DataLoader specific parameters (Validation/Test)
val_loader:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  shuffle: false

# Parameters that vary by Split (Overrides)
overrides:
  train:
    group: "train"
    stride: 1
    steps_per_epoch: 1000
  
  validation:
    group: "validation"
    stride: 6             
    steps_per_epoch: null
