# ----- Base Configuration File -----
input_timesteps: 12
input_channels: 1
hidden_channels: [64, 64, 64]
kernel_size: 7
output_timesteps: 6


defaults:
  - _self_
  - model: unet/direct
  - dataset: gsmap
  - loss: mse_ssim

system:
  num_workers: 4
  pin_memory: true
  sync_bn: false

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  
  checkpoint:
    enabled: true
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/early_stopping
    interval: 5
    save_best: true

  early_stopping:
    enabled: true
    patience: 10
    delta: 0.001
    mode: 'min'

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
