_target_: ainpp_pb_latam.losses.HybridLoss
weights: [1.0, 0.2] # 1.0 for MSE, 0.2 for SSIM

losses:
  # Loss 1: Weighted MSE
  - _target_: ainpp_pb_latam.losses.WeightedMSELoss
    alpha: 2.0
    threshold: 0.0

  # Loss 2: SSIM
  - _target_: ainpp_pb_latam.losses.SSIMLoss
    window_size: 11
    in_channels: 1